// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchTool.Data;

#nullable disable

namespace SearchTool.Data.Migrations
{
    [DbContext(typeof(SearchToolDbContext))]
    partial class SearchToolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchTool.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A high-performance laptop for work and gaming.",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sleek smartphone with a powerful camera.",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise-cancelling headphones for immersive sound.",
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A stylish smartwatch with fitness tracking features.",
                            Name = "Smartwatch"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A lightweight tablet perfect for reading and browsing.",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A next-gen gaming console for an immersive gaming experience.",
                            Name = "Gaming Console"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A high-resolution camera for capturing stunning photos.",
                            Name = "Camera"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A portable Bluetooth speaker with excellent sound quality.",
                            Name = "Bluetooth Speaker"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A reliable external hard drive for data backup.",
                            Name = "External Hard Drive"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A comfortable wireless mouse for everyday use.",
                            Name = "Wireless Mouse"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A mechanical keyboard with customizable RGB lighting.",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A high-resolution monitor for work and gaming.",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A versatile printer for home and office use.",
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A high-speed router for reliable internet connectivity.",
                            Name = "Router"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A smart home hub to control all your smart devices.",
                            Name = "Smart Home Hub"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
