// <auto-generated />
using System;
using InventorySystem.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySystem.Data.Migrations
{
    [DbContext(typeof(InventorySystemDbContext))]
    [Migration("20260717134538_AddLowStockProductView")]
    partial class AddLowStockProductView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventorySystem.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinStock = 10,
                            Name = "Product A",
                            Price = 10.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            MinStock = 20,
                            Name = "Product B",
                            Price = 20.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            MinStock = 30,
                            Name = "Product C",
                            Price = 30.00m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 4,
                            MinStock = 40,
                            Name = "Product D",
                            Price = 40.00m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 5,
                            MinStock = 50,
                            Name = "Product E",
                            Price = 50.00m,
                            Stock = 45
                        });
                });

            modelBuilder.Entity("InventorySystem.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("SaleDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaleDate = new DateTimeOffset(new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TotalAmount = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            SaleDate = new DateTimeOffset(new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TotalAmount = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            SaleDate = new DateTimeOffset(new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TotalAmount = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            SaleDate = new DateTimeOffset(new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TotalAmount = 400.00m
                        });
                });

            modelBuilder.Entity("InventorySystem.Data.Entities.SaleItem", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SaleItems");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 1,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            SaleId = 2,
                            ProductId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            SaleId = 2,
                            ProductId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            SaleId = 3,
                            ProductId = 5,
                            Quantity = 6
                        },
                        new
                        {
                            SaleId = 3,
                            ProductId = 1,
                            Quantity = 7
                        },
                        new
                        {
                            SaleId = 4,
                            ProductId = 2,
                            Quantity = 8
                        },
                        new
                        {
                            SaleId = 4,
                            ProductId = 3,
                            Quantity = 9
                        });
                });

            modelBuilder.Entity("ProductSale", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "SalesId");

                    b.HasIndex("SalesId");

                    b.ToTable("ProductSale");
                });

            modelBuilder.Entity("InventorySystem.Data.Entities.SaleItem", b =>
                {
                    b.HasOne("InventorySystem.Data.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Data.Entities.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ProductSale", b =>
                {
                    b.HasOne("InventorySystem.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Data.Entities.Sale", null)
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySystem.Data.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("InventorySystem.Data.Entities.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
